from agent_graph.state_schema import AgentState
from llm.qwen_wrapper import QwenWrapper

def generate_answer_node(state: AgentState) -> AgentState:
    user_question = state.get("user_text")
    qwen = QwenWrapper()
    prompt = f"""The user's question is as follows:

            “{user_question}”

            Below is the complete image analysis report generated by the system. Please use the information provided, including object recognition, SQL generation, and execution results, to comprehensively judge and answer the user's question. Provide up to five most likely shooting locations, along with specific reasons:
            
            Recognized objects:{state.get("objects")}

            Generated SQL:{state.get("sql_statements")}
            
            The execution result of valid SQL:{state.get("filter_results")}

            Please only provide your final response and refrain from repeating the content of the report."""

    messages = [
        {"role": "system", "content": "You are an expert in image and geographic location inference."},
        {"role": "user", "content": prompt}
    ]
    print(prompt)
    chat_response = qwen.chat(messages)
    new_state = state.copy()
    new_state["summary"] = chat_response
    print("\n================================[Brain Message]=================================\n")
    print(chat_response)
    return new_state



